version: 2.1
orbs:
  # Your orb will be automatically injected here during the pipeline.
  # Reference your orb's jobs and commands below as they will exist when built.
  orb-tools: circleci/orb-tools@12.0
  # The orb definition is intentionally not included here. It will be injected into the pipeline.
  ftest: jimicircleci/fcheck@dev:<<pipeline.git.revision>>
  python: circleci/python@1.2.0

# Use this tag to ensure test jobs always run,
# even though the downstream publish job will only run on release tags.
filters: &filters
  tags:
    only: /.*/

# # Filter for release tags.
# release-filters: &release-filters
#   branches:
#     ignore: /.*/
#   tags:
#     only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  # Create jobs to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-format:
    executor: python/default
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - run: pip install black
      - run: pip install isort
      - ftest/format:
          path: sample_files
          config: pyproject.toml

  command-lint:
    executor: python/default
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - run: pip install flake8
      - ftest/lint:
          path: sample_files
          config: .flake8

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      # Test your orb's commands in a custom job and test your orb's jobs directly as a part of this workflow.
      - command-format:
          filters: *filters
      - ftest/format:
          path: sample_files
          config: pyproject.toml
      - command-lint:
          filters: *filters
      - ftest/lint:
          path: sample_files
          config: .flake8  
      # The orb must be re-packed for publishing, and saved to the workspace.
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb_name: jimicircleci/fcheck
          vcs_type: << pipeline.project.type >>
          pub_type: production
          # Ensure this job requires all test jobs and the pack job.
          requires:
            - orb-tools/pack
            - command-format
            - ftest/format
            - command-lint
            - ftest/lint
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
